# Generated by Django 2.2.6 on 2022-06-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('mean', models.CharField(max_length=200)),
                ('synonym', models.CharField(max_length=40)),
                ('antonym', models.CharField(max_length=40)),
                ('example', models.CharField(max_length=300)),
            ],
        ),
    ]
