# Generated by Django 4.0.5 on 2022-12-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20220604_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavDictMean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('favMean', models.CharField(max_length=50)),
            ],
        ),
    ]
