# Generated by Django 4.0.5 on 2022-12-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_favdictmean'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
