# Generated by Django 4.1.2 on 2022-12-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('img', models.ImageField(default='profile.png', upload_to='profileImage/')),
                ('profession', models.CharField(max_length=60)),
            ],
        ),
    ]
