# Generated by Django 4.1.2 on 2022-12-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('img', models.ImageField(default='', upload_to='User/ProfileImage/')),
                ('QuotesFav', models.TextField(default='')),
                ('MemesFav', models.TextField(default='')),
                ('JokesFav', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
            ],
        ),
    ]
