# Generated by Django 4.0.5 on 2022-12-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_remove_profile_info_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_info',
            old_name='JokesFav',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile_info',
            old_name='MemesFav',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='profile_info',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile_info',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
