# Generated by Django 4.0.5 on 2022-12-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_rename_jokesfav_profile_info_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_info',
            name='desc',
            field=models.EmailField(default='india', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile_info',
            name='address',
            field=models.TextField(default='india'),
        ),
        migrations.AlterField(
            model_name='profile_info',
            name='email',
            field=models.EmailField(default='example123@.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile_info',
            name='img',
            field=models.ImageField(default='logo.svg', upload_to='User/ProfileImage/'),
        ),
        migrations.AlterField(
            model_name='profile_info',
            name='phone',
            field=models.TextField(default='1234567890'),
        ),
        migrations.AlterField(
            model_name='profile_info',
            name='username',
            field=models.CharField(default='Your Name', max_length=60),
        ),
    ]
