# Generated by Django 4.0.5 on 2022-12-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profile_info_desc_alter_profile_info_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_info',
            name='desc',
            field=models.EmailField(default='i am a programmer', max_length=254),
        ),
    ]
