# Generated by Django 4.0.5 on 2022-12-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profile_info_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_info',
            old_name='desc',
            new_name='description',
        ),
    ]
