# Generated by Django 4.0.5 on 2022-12-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_rename_desc_profile_info_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_info',
            name='description',
            field=models.TextField(default='i am a programmer'),
        ),
    ]
