# Generated by Django 4.0.5 on 2022-12-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_alter_profile_info_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_info',
            name='email',
            field=models.EmailField(default='brainpower123@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile_info',
            name='img',
            field=models.ImageField(default='logo.svg', upload_to='upload/'),
        ),
    ]
