# Generated by Django 4.0.5 on 2022-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_alter_profile_info_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_info',
            name='img',
            field=models.ImageField(default='logo.svg', upload_to='static/ProfileImage/'),
        ),
    ]
