# Generated by Django 4.0.5 on 2022-12-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_alter_profile_info_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_info',
            name='email',
            field=models.EmailField(default='example123@.com', max_length=254),
        ),
    ]
