# Generated by Django 4.0.5 on 2022-12-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_alter_profile_info_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_info',
            name='isChannel',
            field=models.BooleanField(default=False),
        ),
    ]
