# Generated by Django 4.0.5 on 2022-12-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContentCreating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='isChannel',
        ),
    ]
