# Generated by Django 4.0.5 on 2022-12-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentCreating', '0004_channel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='')),
                ('title', models.CharField(default='Your Name', max_length=60)),
                ('memesImage', models.ImageField(default='UserCreationMemesImage/default.svg', upload_to='UserCreationMemesImage/')),
                ('type', models.TextField(default='')),
            ],
        ),
    ]
