# Generated by Django 4.0.5 on 2022-12-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentCreating', '0005_memes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='type',
        ),
        migrations.AddField(
            model_name='memes',
            name='memesType',
            field=models.CharField(default='', max_length=130),
        ),
    ]
