# Generated by Django 4.0.5 on 2022-12-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentCreating', '0006_remove_memes_type_memes_memestype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
