# Generated by Django 4.0.5 on 2022-12-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentCreating', '0007_alter_memes_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='', max_length=200)),
                ('JokesImage', models.ImageField(default='UserCreationJokesmage/default.svg', upload_to='UserCreationJokesmage/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('newsTitle', models.CharField(default='', max_length=200)),
                ('newsDescription', models.CharField(default='', max_length=200)),
                ('newsContent', models.CharField(default='', max_length=200)),
                ('newsImage', models.ImageField(default='UserCreationNewsImage/default.svg', upload_to='UserCreationNewsImage/')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=120)),
                ('userQuotes', models.CharField(default='', max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='memes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
