# Generated by Django 2.2.6 on 2022-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
