# Generated by Django 2.2.6 on 2022-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profile_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_info',
            name='username',
            field=models.CharField(default='aksdjf', max_length=60),
        ),
    ]
