# Generated by Django 4.0.5 on 2022-12-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_profile_info_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_info',
            name='img',
            field=models.ImageField(default=1, upload_to='User/img'),
            preserve_default=False,
        ),
    ]
