# Generated by Django 4.0.5 on 2022-12-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_alter_profile_info_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_info',
            name='JokesFav',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile_info',
            name='MemesFav',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile_info',
            name='QuotesFav',
            field=models.TextField(default=''),
        ),
    ]
